"""
Pydantic models for the AgriSphere Recommendation Agent.

The Recommendation Agent is a standalone agent.
It requires only:
    - crop
    - state
    - soil_ph
"""

from typing import List

from pydantic import BaseModel, Field


class RecommendationRequest(BaseModel):
    """
    Input received by the Recommendation Agent.

    Only three inputs are required from the farmer.
    """

    crop: str = Field(
        ...,
        description="Name of the crop being cultivated",
        examples=["Rice"]
    )

    state: str = Field(
        ...,
        description="State where the farm is located",
        examples=["Maharashtra"]
    )

    soil_ph: float = Field(
        ...,
        ge=0,
        le=14,
        description="Soil pH value between 0 and 14",
        examples=[6.0]
    )


class RecommendationItem(BaseModel):
    """
    One agricultural recommendation.
    """

    priority: int = Field(
        ...,
        description="Priority of the recommendation. 1 is highest."
    )

    area: str = Field(
        ...,
        description="Agricultural area concerned by the recommendation."
    )

    recommendation: str = Field(
        ...,
        description="Practical recommendation for the farmer."
    )

    reason: str = Field(
        ...,
        description="Agricultural reason behind the recommendation."
    )


class RecommendationResponse(BaseModel):
    """
    Output generated by the standalone Recommendation Agent.
    """

    crop: str

    state: str

    soil_ph: float

    recommendations: List[RecommendationItem]

    overall_risk: str = Field(
        ...,
        description="Overall agricultural risk: Low, Moderate, High, or Critical."
    )

    overall_advice: str = Field(
        ...,
        description="Short overall farming advice."
    )

    limitations: List[str] = Field(
        default_factory=list,
        description="Important information that was unavailable."
    )